"""AIS decoding.

Reference values come from outside this project: the first two sentences are published
examples with the pyais library's documented decodes, and the rest were generated by
pyais's encoder (pyais is not a dependency; its output is pasted here as fixed data).
"""

import numpy as np
import pytest

from src.rgc_sdr.decoding import DecodeWorker
from src.rgc_sdr.device.source import SequentialReader, _Ring
from src.rgc_sdr.dsp.ais import CHANNELS, AisDecoder, nmea, parse
from src.rgc_sdr.dsp.aprs import crc_x25
from tests.test_aprs import hdlc_levels


def payload_bits(*sentences):
    payload = "".join(s.split(",")[5] for s in sentences)
    fill = int(sentences[-1].split(",")[6].split("*")[0])
    out = []
    for c in payload:
        v = ord(c) - 48
        out += [int(b) for b in f"{v - 8 if v > 40 else v:06b}"]
    return np.array(out[:len(out) - fill], dtype=np.uint8)


# -- parsing, against published and independently generated messages -----------------


def test_published_class_a_position_reports():
    t, mmsi, f = parse(payload_bits("!AIVDM,1,1,,B,15M67FC000G?ufbE`FepT@3n00Sa,0*5C"))
    assert (t, mmsi, f["status"], f["sog"], f["cog"], f["heading"]) == (
        1, 366053209, "restricted manoeuvrability", 0.0, 219.3, 1)
    assert f["position"] == pytest.approx((37.802118, -122.341618), abs=1e-6)
    t, mmsi, f = parse(payload_bits("!AIVDM,1,1,,A,13u?etPv2;0n:dDPwUM1U1Cb069D,0*23"))
    assert (mmsi, f["sog"], f["cog"], f["heading"]) == (265547250, 13.9, 40.4, 41)
    assert f["position"] == pytest.approx((57.660353, 11.832977), abs=1e-6)


def test_class_b_position():
    t, mmsi, f = parse(payload_bits("!AIVDO,1,1,,A,B7Pab6@0@2UpM8JS;j07SwP00000,0*6D"))
    assert (t, mmsi, f["sog"], f["cog"], f["heading"]) == (18, 503999001, 6.4, 12.0, None)
    assert f["position"] == pytest.approx((-38.1, 144.95), abs=1e-5)


def test_base_station_time():
    t, mmsi, f = parse(payload_bits("!AIVDO,1,1,,A,403Ovk1vbRS45:Fmp1bD3p000000,0*51"))
    assert (t, mmsi) == (4, 3669708)
    assert "2026-10-05 03:04:05 UTC" in f["time"]
    assert f["position"] == pytest.approx((-37.9, 144.8), abs=1e-5)


def test_static_and_voyage_data():
    t, mmsi, f = parse(payload_bits(
        "!AIVDO,2,1,0,A,57OkN=P00001H`s7;?A=0U8UB0tJ1@5<l4pT400t000000000011ESkT3lU0,0*24",
        "!AIVDO,2,2,0,A,00000000000,2*26"))
    assert (t, mmsi, f["name"], f["callsign"], f["destination"]) == (
        5, 503111222, "SPIRIT OF TASMANIA", "VJN1234", "to DEVONPORT")


def test_class_b_static_parts():
    _, _, a = parse(payload_bits("!AIVDO,1,1,,A,H7PL:H1<D6098DE`D00000000000,0*6E"))
    _, _, b = parse(payload_bits("!AIVDO,1,1,,A,H7PL:H4U0000000F8Gijkl000000,0*59"))
    assert a["name"] == "SEA BREEZE" and b["callsign"] == "VHW1234"


def test_aid_to_navigation():
    t, mmsi, f = parse(payload_bits(
        "!AIVDO,1,1,,A,E>lsphb`7a:@844V64`@42PR9P05;0TPm2pr000000000000000000000000,4*04"))
    assert (t, mmsi, f["name"], f["aid_type"]) == (21, 995031234, "PORT PHILLIP HEADS",
                                                   "cardinal mark E")
    assert f["position"] == pytest.approx((-38.29, 144.62), abs=1e-5)


def test_sentences_round_trip():
    # The second is widely reprinted ending *23, but its characters XOR to 0x24: a typo
    # that survives because decoders such as pyais do not check. Corrected here.
    for s in ("!AIVDM,1,1,,B,15M67FC000G?ufbE`FepT@3n00Sa,0*5C",
              "!AIVDM,1,1,,A,13u?etPv2;0n:dDPwUM1U1Cb069D,0*24"):
        assert nmea(payload_bits(s), s.split(",")[4]) == [s]


def test_long_messages_are_split_into_sentences():
    bits = payload_bits(
        "!AIVDO,2,1,0,A,57OkN=P00001H`s7;?A=0U8UB0tJ1@5<l4pT400t000000000011ESkT3lU0,0*24",
        "!AIVDO,2,2,0,A,00000000000,2*26")
    out = nmea(bits, "B")
    assert len(out) == 2 and all(len(s) <= 82 for s in out)
    assert out[0].startswith("!AIVDM,2,1,1,B,") and out[1].startswith("!AIVDM,2,2,1,B,")


# -- over the air: GMSK on both channels, through the two-channel worker --------------

RATE = 768_000.0
CENTRE = 162.0e6


def gmsk_burst(bits, rate=RATE, offset_hz=0.0, carrier_error=0.0, damage=False):
    """One AIS transmission: message + FCS, HDLC framed and NRZI'd, Gaussian-filtered
    (BT 0.4), FM at +/-2.4 kHz, `offset_hz` from the centre of a `rate` stream."""
    frame = np.packbits(bits).tobytes()
    crc = crc_x25(frame)
    levels = hdlc_levels(frame + bytes([crc & 0xFF, crc >> 8]), flags=3)
    if damage:
        levels[levels.size // 2] ^= 1                    # one wrong symbol mid-frame
    levels = np.r_[np.tile([0, 1], 12), levels]           # the training sequence
    sps = rate / 9600
    n = int(levels.size * sps)
    nrz = np.where(levels[np.minimum((np.arange(n) / sps).astype(int), levels.size - 1)], 1.0, -1.0)
    t = np.arange(-2 * sps, 2 * sps + 1) / sps
    sigma = np.sqrt(np.log(2)) / (2 * np.pi * 0.4)
    g = np.exp(-t ** 2 / (2 * sigma ** 2))
    shaped = np.convolve(nrz, g / g.sum(), mode="same")
    freq = shaped * 2400.0 + offset_hz + carrier_error
    return np.exp(2j * np.pi * np.cumsum(freq) / rate).astype(np.complex64)


class RingSource:
    def __init__(self, centre=CENTRE):
        self.sample_rate = RATE
        self.center_freq = centre
        self.ring = _Ring(2_000_000)

    def sequential_reader(self):
        return SequentialReader(self.ring)


def _run(worker, iq):
    found = []
    for block in np.array_split(iq, max(1, iq.size // 38400)):
        found += worker.process(block)
    return found


def _noise(n, level=0.02, seed=3):
    rng = np.random.default_rng(seed)
    return (level * (rng.standard_normal(n) + 1j * rng.standard_normal(n))).astype(np.complex64)


def test_decodes_both_channels_at_once():
    name = payload_bits("!AIVDO,1,1,,A,H7PL:H1<D6098DE`D00000000000,0*6E")      # SEA BREEZE
    pos = payload_bits("!AIVDO,1,1,,A,B7Pab6@0@2UpM8JS;j07SwP00000,0*6D")
    pos[8:38] = name[8:38]                                   # the same vessel's MMSI
    gap = np.zeros(int(RATE * 0.05), np.complex64)
    iq = np.concatenate([
        gap,
        gmsk_burst(name, offset_hz=CHANNELS["B"] - CENTRE, carrier_error=1500.0),
        gap,
        gmsk_burst(pos, offset_hz=CHANNELS["A"] - CENTRE, carrier_error=-1500.0),
        gap, gap])
    iq = iq + _noise(iq.size)
    worker = DecodeWorker(RingSource(), "ais")
    found = _run(worker, iq)
    assert [(m.channel, m.msg_type) for m in found] == [("B", 24), ("A", 18)]
    assert found[1].name == "SEA BREEZE"                   # learnt on the other channel
    assert found[1].position == pytest.approx((-38.1, 144.95), abs=1e-5)
    assert found[1].sentences[0].startswith("!AIVDM,1,1,,A,B")
    assert "SEA BREEZE" in found[1].summary()


def test_channels_out_of_view_are_reported_and_skipped():
    worker = DecodeWorker(RingSource(centre=161.5e6), "ais")
    assert [ok for _, _, ok in worker.channels_in_view()] == [False, False]
    worker.source.center_freq = CENTRE
    worker.follow_tuning()
    assert [ok for _, _, ok in worker.channels_in_view()] == [True, True]


def test_listening_offset_does_not_move_fixed_channels():
    worker = DecodeWorker(RingSource(), "ais")
    worker.set_offset(10e3)
    assert worker._lanes[0].chain.offset_hz == pytest.approx(CHANNELS["A"] - CENTRE)


def test_noise_alone_decodes_nothing():
    worker = DecodeWorker(RingSource(), "ais")
    assert _run(worker, _noise(int(RATE * 2), level=0.3)) == []


def test_decoder_rejects_a_damaged_frame():
    bits = payload_bits("!AIVDM,1,1,,B,15M67FC000G?ufbE`FepT@3n00Sa,0*5C")
    burst = gmsk_burst(bits, damage=True)
    dec = AisDecoder(48_000.0)
    from src.rgc_sdr.dsp.demod import DemodChain
    chain = DemodChain(RATE, "nbfm", bandwidth_hz=20e3, agc=False)
    chain.process(np.concatenate([burst, np.zeros(20000, np.complex64)]))
    assert dec.process(chain.last_detected) == []
