"""RDS: the digital data broadcast on FM stations (station name, radio text, type).

Signal chain, from the FM multiplex:

    57 kHz subcarrier (3 x the 19 kHz stereo pilot), BPSK, 1187.5 bit/s,
    biphase coded, differentially encoded, in 26-bit blocks of 16 data + 10 check bits,
    four blocks to a group.

The 57 kHz carrier is regenerated by cubing the pilot phasor. The standard locks the RDS
subcarrier to the third harmonic of the pilot, but not every encoder on air does: Triple M
Melbourne measured about 7 Hz away. So a small Costas-style loop tracks what remains, a
slowly turning phase, using the fact that squaring a BPSK signal removes the data.

Pure NumPy, no Qt, no device access.
"""

from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np

from .decimate import StreamDecimator, lowpass_taps

#: Generator polynomial x^10 + x^8 + x^7 + x^5 + x^4 + x^3 + 1, most significant bit first.
GENERATOR = 0x5B9

#: Offset words added to each block's check bits, telling the blocks apart.
OFFSETS: dict[str, int] = {"A": 0x0FC, "B": 0x198, "C": 0x168, "C'": 0x350, "D": 0x1B4}

#: The syndromes published in IEC 62106. They are written least-significant-bit first
#: relative to the convention used here, with the generator reversed to match. Kept only
#: so a test can confirm the polynomial and offsets above against an independent source.
PUBLISHED_SYNDROMES: dict[str, int] = {
    "A": 0x3D8, "B": 0x3D4, "C": 0x25C, "C'": 0x3CC, "D": 0x258,
}

BIT_RATE = 1187.5
SUBCARRIER_HZ = 57_000.0

#: Programme types, the RDS table used in Europe and Australia (North American RBDS
#: numbers them differently).
PTY_NAMES = (
    "", "News", "Current Affairs", "Information", "Sport", "Education", "Drama",
    "Culture", "Science", "Varied", "Pop Music", "Rock Music", "Easy Listening",
    "Light Classical", "Serious Classical", "Other Music", "Weather", "Finance",
    "Children's", "Social Affairs", "Religion", "Phone-in", "Travel", "Leisure",
    "Jazz Music", "Country Music", "National Music", "Oldies Music", "Folk Music",
    "Documentary", "Alarm Test", "Alarm",
)

_NEXT_BLOCK = {"A": "B", "B": "C", "C": "D", "C'": "D", "D": "A"}
_BLOCK_INDEX = {"A": 0, "B": 1, "C": 2, "C'": 2, "D": 3}


# -- the block code ----------------------------------------------------------

def _mod_generator(value: int) -> int:
    while value.bit_length() > 10:
        value ^= GENERATOR << (value.bit_length() - 11)
    return value


def checkword(info: int, offset: str) -> int:
    """The 10 check bits for a 16-bit data word, with its block's offset applied."""
    return _mod_generator((info & 0xFFFF) << 10) ^ OFFSETS[offset]


def encode_block(info: int, offset: str) -> int:
    """A 26-bit block: 16 data bits then 10 check bits."""
    return ((info & 0xFFFF) << 10) | checkword(info, offset)


def syndrome(block: int) -> int:
    """Zero-offset syndrome of a 26-bit block. Equals the offset word when intact."""
    return _mod_generator(block & 0x3FFFFFF)


_OFFSET_BY_SYNDROME = {value: name for name, value in OFFSETS.items()}


def offset_of(block: int) -> str | None:
    """Which block of a group this is, or None if it is corrupt."""
    return _OFFSET_BY_SYNDROME.get(syndrome(block))


# -- station information -----------------------------------------------------

def _rds_char(code: int) -> str:
    # The RDS character set matches ASCII over the printable range, which is what
    # stations actually send for names and text. Carriage return marks the end of a
    # radio text message and is kept so the end can be found.
    if code == 0x0D:
        return "\r"
    return chr(code) if 0x20 <= code < 0x7F else " "


@dataclass
class StationInfo:
    """What has been decoded so far for the station being received."""

    pi: int | None = None
    pty: int | None = None
    tp: bool = False
    ta: bool = False
    music: bool = False
    ps: list[str] = field(default_factory=lambda: [" "] * 8)
    ps_seen: set[int] = field(default_factory=set)
    rt: list[str] = field(default_factory=lambda: [" "] * 64)
    rt_seen: set[int] = field(default_factory=set)
    rt_ab: int | None = None
    #: The last radio text received in full. Shown instead of the message being
    #: assembled, which arrives four characters at a time and, part-filled, read on
    #: screen as fragments like "el  oo" -- indistinguishable from garbage.
    rt_complete: str = ""
    groups: int = 0

    @property
    def ps_name(self) -> str:
        """The eight-character station name, once all four segments have arrived."""
        return "".join(self.ps).strip() if len(self.ps_seen) == 4 else ""

    @property
    def radio_text(self) -> str:
        return self.rt_complete

    def _check_rt_complete(self, width: int) -> None:
        """Publish the message once every segment up to its end has arrived."""
        text = "".join(self.rt)
        end = text.find("\r")
        last = end // width if end >= 0 else (64 // width) - 1
        if all(segment in self.rt_seen for segment in range(last + 1)):
            self.rt_complete = (text[:end] if end >= 0 else text[: 16 * width]).strip()

    @property
    def pty_name(self) -> str:
        if self.pty is None or not 0 <= self.pty < len(PTY_NAMES):
            return ""
        return PTY_NAMES[self.pty]

    def clear(self) -> None:
        self.__init__()

    def apply(self, blocks: list[int | None]) -> None:
        """Decode one group. `blocks` holds the four 16-bit data words, None if bad."""
        a, b, c, d = blocks
        if a is not None:
            self.pi = a
        if b is None:
            return                   # without block B the group type is unknown
        self.groups += 1
        group_type = (b >> 12) & 0xF
        version_b = bool((b >> 11) & 1)
        self.tp = bool((b >> 10) & 1)
        self.pty = (b >> 5) & 0x1F
        if version_b and c is not None:
            self.pi = c              # version B groups repeat the PI in block C

        if group_type == 0:
            self.ta = bool((b >> 4) & 1)
            self.music = bool((b >> 3) & 1)
            segment = b & 0x3
            if d is not None:
                self.ps[2 * segment] = _rds_char(d >> 8)
                self.ps[2 * segment + 1] = _rds_char(d & 0xFF)
                self.ps_seen.add(segment)
        elif group_type == 2:
            ab = (b >> 4) & 1
            if self.rt_ab is not None and ab != self.rt_ab:
                # The A/B flag flips when the station starts a new message.
                self.rt = [" "] * 64
                self.rt_seen.clear()
            self.rt_ab = ab
            segment = b & 0xF
            if not version_b:
                if c is not None and d is not None:
                    for i, word in ((0, c), (2, d)):
                        self.rt[4 * segment + i] = _rds_char(word >> 8)
                        self.rt[4 * segment + i + 1] = _rds_char(word & 0xFF)
                    self.rt_seen.add(segment)
                    self._check_rt_complete(4)
            elif d is not None:
                self.rt[2 * segment] = _rds_char(d >> 8)
                self.rt[2 * segment + 1] = _rds_char(d & 0xFF)
                self.rt_seen.add(segment)
                self._check_rt_complete(2)


class GroupAssembler:
    """Find block boundaries in a bit stream and hand complete groups to a StationInfo.

    Sync is declared only when two consecutive blocks carry the offsets they should in
    sequence, so a random 26-bit window that happens to check out cannot start it. Once
    synchronised, a run of bad blocks drops sync and the search starts again.
    """

    def __init__(self, info: StationInfo | None = None, lose_after: int = 12) -> None:
        self.info = info or StationInfo()
        self.lose_after = lose_after
        self._register = 0
        self._count = 0
        self._synced = False
        self._candidate: tuple[int, str] | None = None
        self._since_block = 0
        self._expect = "A"
        self._blocks: list[int | None] = [None] * 4
        self._bad_run = 0
        self.good_blocks = 0
        self.bad_blocks = 0

    @property
    def synced(self) -> bool:
        return self._synced

    def reset(self) -> None:
        self.__init__(StationInfo(), self.lose_after)

    def push(self, bits: np.ndarray) -> None:
        for bit in bits:
            self._register = ((self._register << 1) | int(bit)) & 0x3FFFFFF
            self._count += 1
            if self._synced:
                self._synced_bit()
            else:
                self._search_bit()

    def _search_bit(self) -> None:
        if self._count < 26:
            return
        name = offset_of(self._register)
        if name is None:
            return
        if self._candidate is not None:
            position, previous = self._candidate
            if self._count - position == 26 and _NEXT_BLOCK[previous] in (name, "C" if name == "C'" else name):
                self._synced = True
                self._since_block = 0
                self._expect = _NEXT_BLOCK[name]
                self._blocks = [None] * 4
                self._store(name, self._register)
                self._bad_run = 0
                return
        self._candidate = (self._count, name)

    def _store(self, name: str, block: int) -> None:
        index = _BLOCK_INDEX[name]
        self._blocks[index] = block >> 10
        self.good_blocks += 1
        if index == 3:
            self.info.apply(self._blocks)
            self._blocks = [None] * 4

    def _synced_bit(self) -> None:
        self._since_block += 1
        if self._since_block < 26:
            return
        self._since_block = 0
        expected = self._expect
        name = offset_of(self._register)
        allowed = {"C", "C'"} if expected == "C" else {expected}
        if name in allowed:
            self._store(name, self._register)
            self._bad_run = 0
        else:
            self.bad_blocks += 1
            self._bad_run += 1
            index = _BLOCK_INDEX[expected]
            self._blocks[index] = None
            if index == 3:
                self.info.apply(self._blocks)
                self._blocks = [None] * 4
            if self._bad_run >= self.lose_after:
                self._synced = False
                self._candidate = None
        self._expect = _NEXT_BLOCK["C" if expected == "C" else expected]


# -- from the multiplex to bits ----------------------------------------------

# Carrier loop: update every 64 samples (about 3 bits at 24 kHz). Gains chosen on a
# recording of Triple M Melbourne: block error rate 45% with a fixed phase, 0.1% tracked.
CARRIER_CHUNK = 64
CARRIER_KP = 0.3
CARRIER_KI = 0.02

class RdsDemodulator:
    """Recover RDS bits from the multiplex and pass them to a GroupAssembler.

    Needs the multiplex and the unit pilot phasor, time-aligned, as StereoDecoder provides
    them: the 57 kHz subcarrier is regenerated as the cube of the pilot.
    """

    def __init__(self, mpx_rate: float) -> None:
        from .filters import Fir, fir_length_for

        self.mpx_rate = float(mpx_rate)
        factor = 1
        while self.mpx_rate / (factor * 2) >= 16_000.0:
            factor *= 2
        self._down = StreamDecimator(factor)
        self.rate = self.mpx_rate / factor
        cutoff = 2_400.0 / self.rate
        self._lowpass = Fir(lowpass_taps(cutoff, fir_length_for(cutoff)))
        self._spb = self.rate / BIT_RATE                   # samples per bit, fractional
        self._half = max(1, int(round(self._spb / 2.0)))
        self._template = np.concatenate([np.ones(self._half), -np.ones(self._half)])
        self._gate = max(1, int(round(self._spb / 8.0)))
        self.clock_gain = 0.5
        # Carrier tracking: phase (radians) and frequency (radians per sample) of the
        # residual subcarrier after mixing with the cubed pilot.
        self._theta = 0.0
        self._freq = 0.0
        self._buffer = np.zeros(0, dtype=np.float64)
        self._start = 0                   # absolute index of _buffer[0]
        self._next = None                 # absolute position of the next bit, or None
        self._previous = 0
        self.assembler = GroupAssembler()

    @property
    def info(self) -> StationInfo:
        return self.assembler.info

    def reset(self) -> None:
        self.__init__(self.mpx_rate)

    def _correlate(self, index: int) -> float:
        segment = self._buffer[index: index + self._template.size]
        if segment.size < self._template.size:
            return 0.0
        return float(np.dot(segment, self._template))

    def _acquire(self) -> None:
        """Choose the bit phase that maximises matched-filter energy over the buffer."""
        span = int(self._spb * 40)
        if self._buffer.size < span + self._template.size:
            return
        best, best_score = 0.0, -1.0
        for step in range(int(self._spb * 4)):
            phase = step / 4.0
            positions = (phase + np.arange(40) * self._spb).astype(int)
            score = sum(abs(self._correlate(p)) for p in positions)
            if score > best_score:
                best, best_score = phase, score
        self._next = self._start + best

    def _track_carrier(self, baseband: np.ndarray) -> np.ndarray:
        """Derotate the subcarrier to a real BPSK signal, following any frequency offset.

        Works in short chunks: within each, BPSK squared leaves twice the phase error
        with the data removed, and a proportional-plus-integral update steers phase
        and frequency for the next chunk.
        """
        real = np.empty(baseband.size, dtype=np.float64)
        for start in range(0, baseband.size, CARRIER_CHUNK):
            chunk = baseband[start: start + CARRIER_CHUNK]
            steps = np.arange(chunk.size)
            rotated = chunk * np.exp(-1j * (self._theta + self._freq * steps))
            real[start: start + chunk.size] = rotated.real
            error = 0.5 * float(np.angle(np.mean(rotated * rotated)))
            self._freq += CARRIER_KI * error / CARRIER_CHUNK
            self._theta = (self._theta + self._freq * chunk.size + CARRIER_KP * error) % (2 * np.pi)
        return real

    def process(self, mpx: np.ndarray, pilot: np.ndarray) -> int:
        """Feed an aligned block of multiplex and pilot. Returns bits recovered."""
        if mpx.size == 0:
            return 0
        baseband = mpx * np.conj(pilot * pilot * pilot)
        baseband = self._lowpass.process(self._down.process(baseband))
        if baseband.size == 0:
            return 0

        real = self._track_carrier(baseband)

        self._buffer = np.concatenate([self._buffer, real])
        if self._next is None:
            self._acquire()
            if self._next is None:
                return 0

        bits = []
        limit = self._start + self._buffer.size - self._template.size - self._gate - 1
        while self._next <= limit:
            index = int(round(self._next)) - self._start
            value = self._correlate(index)
            early = abs(self._correlate(index - self._gate)) if index >= self._gate else 0.0
            late = abs(self._correlate(index + self._gate))
            # Early-late gate: steer towards the side with more energy. Normalised, so
            # the loop behaves the same whatever the signal level.
            total = early + late
            nudge = self.clock_gain * self._gate * (late - early) / total if total > 0 else 0.0
            self._next += self._spb + nudge
            bit = 1 if value > 0 else 0
            bits.append(bit ^ self._previous)             # differential decoding
            self._previous = bit

        # Keep only what the next bit still needs.
        keep_from = int(self._next) - self._start - self._gate - 1
        if keep_from > 0:
            self._buffer = self._buffer[keep_from:]
            self._start += keep_from
        if bits:
            self.assembler.push(np.array(bits, dtype=np.uint8))
        return len(bits)
